// declare module 'react-financial-charts';
// declare module 'react-financial-charts/lib/series';
// declare module 'react-financial-charts/lib/axes';
// declare module 'react-financial-charts/lib/coordinates';
// declare module 'react-financial-charts/lib/scale';
// declare module 'react-financial-charts/lib/tooltip';
// declare module 'react-financial-charts/lib/indicator';
// declare module 'react-financial-charts/lib/helper';
// declare module 'react-financial-charts/lib/utils';
